@startuml
class MainWindow 
class OptionsDialog 
class PresetManagerDialog
class Preset

class PresetManager {
     +void addPreset()
     -List<Preset> presets
     +getPresets()
}

MainWindow -left> OptionsDialog
MainWindow -> PresetManagerDialog
PresetManagerDialog  -> "1" PresetManager
PresetManager  -> "*" Preset
Preset <<creates>>
@enduml


